run:
  tests: false
  timeout: 5m
  go: "1.23"
  modules-download-mode: readonly
linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - bodyclose
    - containedctx
#     - contextcheck
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
#    - exhaustive
#     - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goheader
    - goimports
#     - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
#    - ireturn
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
#     - noctx
    - nolintlint
#     - nonamedreturns
    - nosprintfhostport
    - predeclared
#     - promlinter
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usetesting
    - whitespace
    - wrapcheck
