{
 "title": "Resolver",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queue Size Per Resolver Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(elasti_resolver_queued_count) by (pod)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(elasti_resolver_incoming_requests_bucket[2m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(elasti_resolver_incoming_requests_bucket[2m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(elasti_resolver_incoming_requests_bucket[2m])) by (le))",
     "legendFormat": "P80"
    }
   ]
  },
  {
   "title": "Incoming Request Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(elasti_resolver_incoming_requests_count{}[2m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Resolver - Host Extraction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(elasti_resolver_host_extraction_count[2m])) by (extractionType)",
     "legendFormat": "{{extractionType}}"
    }
   ]
  },
  {
   "title": "Informer Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(elasti_operator_informer_counter{error!=\"\"}[2m])) by (crd_name, action, error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRD Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(elasti_operator_CRD_update_counter[2m])) by (crd_name, mode, error)",
     "legendFormat": "{{crd_name}}-{{mode}}-{{error}}"
    }
   ]
  },
  {
   "title": "Resolver - Operator RPC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(elasti_resolver_operator_rpc_count[2m])) by (error)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Current Informers",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasti_operator_informer_count) by (informer_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CRD Finalizer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(elasti_operator_CRD_finalizer_counter[2m])) by (crd_name, error)",
     "legendFormat": "{{crd_name}}-{{error}}"
    }
   ]
  },
  {
   "title": "Resolve - Traffic Control",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(elasti_resolver_traffic_switch_count[5m])) by (source, enabled)",
     "legendFormat": "{{enabled}}-{{source}}"
    }
   ]
  }
 ]
}