{
 "title": "Elasti",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU - Controller",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"elasti\", container=\"manager\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (kube_pod_container_resource_requests{namespace=\"elasti\", container=\"manager\", resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max (kube_pod_container_resource_limits{namespace=\"elasti\", container=\"manager\", resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "RAM - Controller",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{namespace=\"elasti\", container=\"manager\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (kube_pod_container_resource_requests{container=\"manager\", namespace=\"elasti\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{container=\"manager\", namespace=\"elasti\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Informers - Success",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(elasti_operator_informer_counter{error=\"success\"}[2m])) by (crd_name, action, error)",
     "legendFormat": "{{action}}-{{crd_name}}"
    }
   ]
  },
  {
   "title": "Handlers - Success",
   "type": "timeseries",
   "description": "Handler is passed to the informer as a callback function to handle changes.",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(elasti_operator_informer_handler_counter{error=\"success\"}[2m])) by (key, error)",
     "legendFormat": "{{key}}-{{error}}"
    }
   ]
  },
  {
   "title": "Current Modes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasti_operator_mode) by (crd_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Informers",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasti_operator_informer_count) by (informer_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Informers - Error",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(elasti_operator_informer_counter{error!=\"success\"}[2m])) by (crd_name, action, error)",
     "legendFormat": "{{action}}-{{crd_name}}-{{error}}"
    }
   ]
  },
  {
   "title": "Handlers - Error",
   "type": "timeseries",
   "description": "Handler is passed to the informer as a callback function to handle changes.",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(elasti_operator_informer_handler_counter{error!=\"success\"}[2m])) by (key, error)",
     "legendFormat": "{{key}}-{{error}}"
    }
   ]
  },
  {
   "title": "CRD Updates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(elasti_operator_CRD_update_counter[2m])) by (crd_name, mode, error)",
     "legendFormat": "{{crd_name}}-{{mode}}-{{error}}"
    }
   ]
  },
  {
   "title": "CRD Reconcile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(elasti_operator_reconcile_bucket[2m])) by (crd_name, le))",
     "legendFormat": "P99-{{crd_name}}"
    }
   ]
  },
  {
   "title": "CRD Finalizer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(elasti_operator_CRD_finalizer_counter[2m])) by (crd_name, error)",
     "legendFormat": "{{crd_name}}-{{error}}"
    }
   ]
  },
  {
   "title": "Target Scaled Up",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(elasti_operator_scale_counter[2m])) by (target, error)",
     "legendFormat": "{{target}}-{{error}}"
    }
   ]
  },
  { "title": "Resolver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU - Resolver",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"elasti\", container=\"proxy\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (kube_pod_container_resource_requests{namespace=\"elasti\", container=\"proxy\", resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max (kube_pod_container_resource_limits{namespace=\"elasti\", container=\"proxy\", resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "RAM - Resolver",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{namespace=\"elasti\", container=\"proxy\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (kube_pod_container_resource_requests{container=\"proxy\", namespace=\"elasti\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{container=\"proxy\", namespace=\"elasti\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Incoming Request Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(elasti_resolver_incoming_requests_count{}[2m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(elasti_resolver_incoming_requests_bucket[2m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(elasti_resolver_incoming_requests_bucket[2m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(elasti_resolver_incoming_requests_bucket[2m])) by (le))",
     "legendFormat": "P80"
    }
   ]
  },
  {
   "title": "Queue Size Per Resolver Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(elasti_resolver_queued_count) by (pod)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Resolver - Operator RPC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(elasti_resolver_operator_rpc_count[2m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Resolve - Traffic Control",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(elasti_resolver_traffic_switch_count[5m])) by (source, enabled)",
     "legendFormat": "{{enabled}}-{{source}}"
    }
   ]
  },
  {
   "title": "Resolver - Host Extraction",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(elasti_resolver_host_extraction_count[2m])) by (extractionType)",
     "legendFormat": "{{extractionType}}"
    }
   ]
  }
 ]
}